#!/bin/bash
# shellcheck disable=SC2034

# stdlib testing theme library

builtin set -eo pipefail

STDLIB_TESTING_THEME_DEBUG_FIXTURE="GREY"
STDLIB_TESTING_THEME_ERROR="LIGHT_RED"
STDLIB_TESTING_THEME_LOAD="GREY"
STDLIB_TESTING_THEME_PARAMETRIZE_HIGHLIGHT="LIGHT_BLUE"
STDLIB_TESTING_THEME_PARAMETRIZE_ORIGINAL_TEST_NAMES="GREY"
