#!/bin/bash
# shellcheck disable=SC2034

# stdlib testing variables library

builtin set -eo pipefail

# globals
builtin declare STDLIB_TESTING_PROTECT_PREFIX=""
builtin declare __STDLIB_TESTING_MOCK_SEQUENCE_LOCK_NAME
__STDLIB_TESTING_MOCK_SEQUENCE_LOCK_NAME="__stdlib_testing_internal__mock_sequence_lock"
builtin declare __STDLIB_TESTING_MOCK_SEQUENCE_TRACKING_BOOLEAN
__STDLIB_TESTING_MOCK_SEQUENCE_TRACKING_BOOLEAN="0"

# keywords
builtin declare STDLIB_TESTING_PARAMETRIZE_SETTING_DEBUG_BOOLEAN=""
builtin declare STDLIB_TESTING_PARAMETRIZE_SETTING_FIELD_SEPARATOR=""
builtin declare STDLIB_TESTING_PARAMETRIZE_SETTING_FIXTURE_COMMAND_PREFIX=""
builtin declare STDLIB_TESTING_PARAMETRIZE_SETTING_PREFIX=""
builtin declare STDLIB_TESTING_PARAMETRIZE_SETTING_SHOW_ORIGINAL_TEST_NAMES_BOOLEAN=""
builtin declare STDLIB_TESTING_PARAMETRIZE_SETTING_VARIANT_TAG=""
builtin declare STDLIB_TESTING_TRACEBACK_REGEX=""

# reserved
builtin declare -a __STDLIB_TESTING_MOCK_REGISTERED_INSTANCES_ARRAY
__STDLIB_TESTING_MOCK_REGISTERED_INSTANCES_ARRAY=()
builtin declare __STDLIB_TESTING_MOCK_REGISTRY_FOLDER=""
builtin declare -a __STDLIB_TESTING_MOCK_RESTRICTED_ATTRIBUTES
__STDLIB_TESTING_MOCK_RESTRICTED_ATTRIBUTES=(
  "builtin"
  "case"
  "do"
  "done"
  "elif"
  "else"
  "esac"
  "fi"
  "for"
  "if"
  "while"
)
builtin declare -a __STDLIB_TESTING_MOCK_SEQUENCE_ARRAY
__STDLIB_TESTING_MOCK_SEQUENCE_ARRAY=()
builtin declare __STDLIB_TESTING_MOCK_SEQUENCE_FILENAME=""
builtin declare -a __STDLIB_TESTING_PARAMETRIZE_GENERATED_FUNCTIONS_ARRAY
__STDLIB_TESTING_PARAMETRIZE_GENERATED_FUNCTIONS_ARRAY=()
