#!/bin/bash
# shellcheck disable=SC2034

# stdlib testing variables library

builtin set -eo pipefail

# globals
STDLIB_TESTING_PROTECT_PREFIX=""
__STDLIB_TESTING_MOCK_SEQUENCE_LOCK_NAME="__stdlib_testing_internal__mock_sequence_lock"
__STDLIB_TESTING_MOCK_SEQUENCE_TRACKING_BOOLEAN="0"

# keywords
STDLIB_TESTING_PARAMETRIZE_SETTING_DEBUG_BOOLEAN=""
STDLIB_TESTING_PARAMETRIZE_SETTING_FIELD_SEPARATOR=""
STDLIB_TESTING_PARAMETRIZE_SETTING_FIXTURE_COMMAND_PREFIX=""
STDLIB_TESTING_PARAMETRIZE_SETTING_PREFIX=""
STDLIB_TESTING_PARAMETRIZE_SETTING_SHOW_ORIGINAL_TEST_NAMES_BOOLEAN=""
STDLIB_TESTING_PARAMETRIZE_SETTING_VARIANT_TAG=""
STDLIB_TESTING_TRACEBACK_REGEX=""

# reserved
__STDLIB_TESTING_MOCK_REGISTERED_INSTANCES_ARRAY=()
__STDLIB_TESTING_MOCK_REGISTRY_FOLDER=""
__STDLIB_TESTING_MOCK_RESTRICTED_ATTRIBUTES=(
  "builtin"
  "case"
  "do"
  "done"
  "elif"
  "else"
  "esac"
  "fi"
  "for"
  "if"
  "while"
)
__STDLIB_TESTING_MOCK_SEQUENCE_ARRAY=()
__STDLIB_TESTING_MOCK_SEQUENCE_FILENAME=""
__STDLIB_TESTING_PARAMETRIZE_GENERATED_FUNCTIONS_ARRAY=()
