#!/bin/bash
# shellcheck disable=SC2034

# stdlib colour state disabled library

builtin set -eo pipefail

stdlib.setting.colour.state.disabled() {
  STDLIB_COLOUR_NC=""
  STDLIB_COLOUR_BLACK=""
  STDLIB_COLOUR_RED=""
  STDLIB_COLOUR_GREEN=""
  STDLIB_COLOUR_YELLOW=""
  STDLIB_COLOUR_BLUE=""
  STDLIB_COLOUR_PURPLE=""
  STDLIB_COLOUR_CYAN=""
  STDLIB_COLOUR_WHITE=""
  STDLIB_COLOUR_GREY=""
  STDLIB_COLOUR_LIGHT_RED=""
  STDLIB_COLOUR_LIGHT_GREEN=""
  STDLIB_COLOUR_LIGHT_YELLOW=""
  STDLIB_COLOUR_LIGHT_BLUE=""
  STDLIB_COLOUR_LIGHT_PURPLE=""
  STDLIB_COLOUR_LIGHT_CYAN=""
  STDLIB_COLOUR_LIGHT_WHITE=""
}
