#!/bin/bash
# shellcheck disable=SC2034

# stdlib variables library

builtin set -eo pipefail

# globals
builtin export STDLIB_LOCK_WORKSPACE=""
STDLIB_BUILTIN_ALLOW_OVERRIDE_BOOLEAN=""
STDLIB_CLEANUP_FN_TARGETS_ARRAY=()
STDLIB_COLOUR_NULL=""
STDLIB_COLOUR_SILENT_FALLBACK_BOOLEAN=""
STDLIB_DIRECTORY="$(dirname -- "${BASH_SOURCE[0]}")" # noqa
STDLIB_HANDLER_ERR_FN_ARRAY=()
STDLIB_HANDLER_EXIT_FN_ARRAY=()
STDLIB_TEXTDOMAINDIR="$(dirname -- "${STDLIB_DIRECTORY}")/locales" # noqa
STDLIB_TRACEBACK_DISABLE_BOOLEAN="${STDLIB_TRACEBACK_DISABLE_BOOLEAN:-1}"
__STDLIB_SECURE_DISTRIBUTION="${__STDLIB_SECURE_DISTRIBUTION:-"0"}"

# keywords
STDLIB_ARGS_CALLER_FN_NAME=""
STDLIB_ARGS_NULL_SAFE_ALL_BOOLEAN=""
STDLIB_ARGS_NULL_SAFE_ARRAY=()
STDLIB_FIELD_DELIMITER=""
STDLIB_FIELD_DELIMITER_ENCODE_CHAR=""
STDLIB_KW_SOURCE_VAR=""
STDLIB_LOCK_PERMISSION_OCTAL=""
STDLIB_LOCK_POLLING_INTERVAL=""
STDLIB_LOCK_QUIET_FAILURE_BOOLEAN=""
STDLIB_LOCK_WAIT_SECONDS=""
STDLIB_LOCK_WORKSPACE_PERMISSION_OCTAL=""
STDLIB_LOGGING_MESSAGE_PREFIX=""
STDLIB_PIPEABLE_STDIN_SOURCE_SPECIFIER=""
STDLIB_STDIN_PASSWORD_MASK_BOOLEAN=""
STDLIB_VALIDATION_SOURCE_VAR=""
STDLIB_WRAP_LINE_BREAK_FORCE_CHAR=""
STDLIB_WRAP_PREFIX=""

# reserved
STDLIB_DEFERRED_FN_ARRAY=("stdlib.fn.derive.pipeable" "stdlib.fn.derive.var")
STDLIB_DEFERRED_FN_ARRAY_CALLS_ARRAY=()
__STDLIB_LOGGING_DECORATORS_ARRAY=("_testing.__protected")
