#!/bin/bash
# shellcheck disable=SC2034

# stdlib variables library

builtin set -eo pipefail

# globals
builtin declare -x STDLIB_LOCK_WORKSPACE
STDLIB_LOCK_WORKSPACE=""
builtin declare STDLIB_BUILTIN_ALLOW_OVERRIDE_BOOLEAN=""
builtin declare -a STDLIB_CLEANUP_FN_TARGETS_ARRAY
STDLIB_CLEANUP_FN_TARGETS_ARRAY=()
builtin declare STDLIB_COLOUR_NULL=""
builtin declare STDLIB_COLOUR_SILENT_FALLBACK_BOOLEAN=""
builtin declare STDLIB_DIRECTORY
STDLIB_DIRECTORY="$(dirname -- "${BASH_SOURCE[0]}")" # noqa
builtin declare -a STDLIB_HANDLER_ERR_FN_ARRAY
STDLIB_HANDLER_ERR_FN_ARRAY=()
builtin declare -a STDLIB_HANDLER_EXIT_FN_ARRAY
STDLIB_HANDLER_EXIT_FN_ARRAY=()
builtin declare STDLIB_TEXTDOMAINDIR
STDLIB_TEXTDOMAINDIR="$(dirname -- "${STDLIB_DIRECTORY}")/locales" # noqa
builtin declare STDLIB_TRACEBACK_DISABLE_BOOLEAN
STDLIB_TRACEBACK_DISABLE_BOOLEAN="${STDLIB_TRACEBACK_DISABLE_BOOLEAN:-1}"
builtin declare __STDLIB_SECURE_DISTRIBUTION
__STDLIB_SECURE_DISTRIBUTION="${__STDLIB_SECURE_DISTRIBUTION:-"0"}"

# keywords
builtin declare STDLIB_ARGS_CALLER_FN_NAME=""
builtin declare STDLIB_ARGS_NULL_SAFE_ALL_BOOLEAN=""
builtin declare -a STDLIB_ARGS_NULL_SAFE_ARRAY
STDLIB_ARGS_NULL_SAFE_ARRAY=()
builtin declare STDLIB_FIELD_DELIMITER=""
builtin declare STDLIB_FIELD_DELIMITER_ENCODE_CHAR=""
builtin declare STDLIB_KW_SOURCE_VAR=""
builtin declare STDLIB_LOCK_PERMISSION_OCTAL=""
builtin declare STDLIB_LOCK_POLLING_INTERVAL=""
builtin declare STDLIB_LOCK_QUIET_FAILURE_BOOLEAN=""
builtin declare STDLIB_LOCK_WAIT_SECONDS=""
builtin declare STDLIB_LOCK_WORKSPACE_PERMISSION_OCTAL=""
builtin declare STDLIB_LOGGING_MESSAGE_PREFIX=""
builtin declare STDLIB_PIPEABLE_STDIN_SOURCE_SPECIFIER=""
builtin declare STDLIB_STDIN_PASSWORD_MASK_BOOLEAN=""
builtin declare STDLIB_VALIDATION_SOURCE_VAR=""
builtin declare STDLIB_WRAP_LINE_BREAK_FORCE_CHAR=""
builtin declare STDLIB_WRAP_PREFIX=""

# reserved
builtin declare -a STDLIB_DEFERRED_FN_ARRAY
STDLIB_DEFERRED_FN_ARRAY=("stdlib.fn.derive.pipeable" "stdlib.fn.derive.var")
builtin declare -a STDLIB_DEFERRED_FN_ARRAY_CALLS_ARRAY
STDLIB_DEFERRED_FN_ARRAY_CALLS_ARRAY=()
builtin declare -a __STDLIB_LOGGING_DECORATORS_ARRAY
__STDLIB_LOGGING_DECORATORS_ARRAY=("_testing.__protected")
